name: Build & deploy dev
on: push
jobs:
  dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup dev env
        run: |
          echo REACT_APP_backend_url=$backend_url > .env
          echo REACT_APP_backend_api_key=$backend_api_key >> .env
          echo REACT_APP_google_client_id=$google_client_id >> .env
        env:
          backend_url: "https://ywdi37qne9.execute-api.eu-north-1.amazonaws.com/api/v1"
          backend_api_key: ${{ secrets.BACKEND_API_KEY_DEV }}
          google_client_id: ${{ secrets.GOOGLE_CLIENT_ID_DEV }}

      - uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install & build dev
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - run: npm install
      - run: npm run build

      - name: Push to s3 bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: dev.timereport.codelabs.se
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: "build"
