name: Build & deploy prod
on:
  workflow_run:
    workflows: ["Build & deploy dev"]
    branches: [master]
    types:
      - completed

jobs:
  prod:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup prod env
        run: |
          echo REACT_APP_backend_url=$backend_url > .env
          echo REACT_APP_backend_api_key=$backend_api_key >> .env
          echo REACT_APP_google_client_id=$google_client_id >> .env
        env:
          backend_url: "https://uwxrroffo0.execute-api.eu-north-1.amazonaws.com/api/v1"
          backend_api_key: ${{ secrets.BACKEND_API_KEY_PROD }}
          google_client_id: ${{ secrets.GOOGLE_CLIENT_ID_PROD }}

      - uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install & build prod
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - run: npm install
      - run: npm run build

      - name: Push to s3 bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: timereport.codelabs.se
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: "build"
